services:
  # Web Service (FastAPI Backend)
  - type: web
    name: meetupio-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meetupio-db
          property: connectionString
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: '["https://https://meet-up-io-git-main-ajs-projects-09f3223e.vercel.app", "http://localhost:3000"]'
      - key: PROJECT_NAME
        value: "Midway API"

databases:
  # PostgreSQL Database
  - name: meetupio-db
    databaseName: midway
    user: midway
